/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'reasonForVisit' : string,
  'preferredDoctor' : string,
  'name' : string,
  'appointmentDate' : string,
  'email' : string,
  'phone' : string,
}
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Doctor {
  'patientsCount' : bigint,
  'name' : string,
  'experience' : bigint,
  'specialty' : string,
  'rating' : number,
}
export interface Service { 'title' : string, 'description' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppointment' : ActorMethod<[Appointment], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'addDoctor' : ActorMethod<[Doctor], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDoctor' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDoctor' : ActorMethod<[bigint, Doctor], undefined>,
  'updateService' : ActorMethod<[bigint, Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];